import React from 'react';

const Projects = () => {
  return (
    <div className="container">
      <div className="project">
        <h2>Projects</h2>
        <div className='projectitem'>
        <h3>Project 1: Promptopia</h3>
        <p>
          About
          Promptopia is your go-to open-source AI prompting tool, 
          designed to ignite your creativity.
        </p>
        <p> 
          Discover, create, 
          and share captivating prompts generated by advanced artificial intelligence.
          Dive into the world of inspiration with Promptopia!
        </p>
        <p>
          Role: Full Stack Developer
        </p>
        <p>
          Technologies Used:
          <li>Next.js: The foundation for building React applications with server-side rendering.</li>
          <li>AI Algorithms: Advanced algorithms power our prompt generation, providing unique and engaging content.</li>
          <li>Tailwind CSS: A utility-first CSS framework for building modern and responsive designs.</li>
        </p>
        <p>
          Usage: 
          <li>The home page provides an introduction to Promptopia, highlighting its purpose and features.</li>
          <li>The main feature is the interactive feed where you can discover a variety of AI-generated prompts.</li>
          <li>Embrace your creativity and use these prompts as a starting point for your artistic endeavors.</li>
        </p>
        <p>
          Outcome: 
          <li>The Promptopia website effectively communicates its purpose as an AI prompting tool for igniting creativity. </li>
          <li>It features clear instructions for getting started, guidelines for usage and contributions, and acknowledges the technologies used.</li>
          <li>The user-friendly interface and transparent information make it a valuable resource for creative individuals.</li>
        </p>
        <p>
          <a href="https://github.com/gaureshpai/promtopia" target='blank'>GitHub Repository</a>
        </p>
        <p>
          <a href="https://ggpromtopia.vercel.app/" target='blank'>Live Demo</a>
        </p>
      </div>
      <hr></hr>
      <div className='projectitem'>
          <h3>Project 2: Promptopia</h3>
          <p>
            About
            Promptopia is your go-to open-source AI prompting tool,
            designed to ignite your creativity.
          </p>
          <p>
            Discover, create,
            and share captivating prompts generated by advanced artificial intelligence.
            Dive into the world of inspiration with Promptopia!
          </p>
          <p>
            Role: Full Stack Developer
          </p>
          <p>
            Technologies Used:
            <li>Next.js: The foundation for building React applications with server-side rendering.</li>
            <li>AI Algorithms: Advanced algorithms power our prompt generation, providing unique and engaging content.</li>
            <li>Tailwind CSS: A utility-first CSS framework for building modern and responsive designs.</li>
          </p>
          <p>
            Usage:
            <li>The home page provides an introduction to Promptopia, highlighting its purpose and features.</li>
            <li>The main feature is the interactive feed where you can discover a variety of AI-generated prompts.</li>
            <li>Embrace your creativity and use these prompts as a starting point for your artistic endeavors.</li>
          </p>
          <p>
            Outcome:
            <li>The Promptopia website effectively communicates its purpose as an AI prompting tool for igniting creativity. </li>
            <li>It features clear instructions for getting started, guidelines for usage and contributions, and acknowledges the technologies used.</li>
            <li>The user-friendly interface and transparent information make it a valuable resource for creative individuals.</li>
          </p>
          <p>
            <a href="https://github.com/gaureshpai/promtopia" target='blank'>GitHub Repository</a>
          </p>
          <p>
            <a href="https://ggpromtopia.vercel.app/" target='blank'>Live Demo</a>
          </p>
        </div>
      </div>
      </div> 
  );
};

export default Projects;
