import React from 'react';

const Projects = () => {
  return (
    <div className="container">
      <div className="project">
        <h2>Projects</h2>
        <div className='projectitem'>
          <h3>Project 1: Promptopia</h3>
          <p>
            About:
            Promptopia is your go-to open-source AI prompting tool,
            designed to ignite your creativity.
          </p>
          <p>
            Discover, create,
            and share captivating prompts generated by advanced artificial intelligence.
            Dive into the world of inspiration with Promptopia!
          </p>
          <p>
            Role: Full Stack Developer
          </p>
          <div>
            <p>Technologies Used:</p>
            <ul>
              <li>Next.js: The foundation for building React applications with server-side rendering.</li>
              <li>AI Algorithms: Advanced algorithms power our prompt generation, providing unique and engaging content.</li>
              <li>Tailwind CSS: A utility-first CSS framework for building modern and responsive designs.</li>
            </ul>
          </div>
          <div>
            <p>Outcome:</p>
            <ul>
              <li>The Promptopia website effectively communicates its purpose as an AI prompting tool for igniting creativity. </li>
              <li>It features clear instructions for getting started, guidelines for usage and contributions, and acknowledges the technologies used.</li>
              <li>The user-friendly interface and transparent information make it a valuable resource for creative individuals.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/promtopia" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
            <p><a href="https://ggpromtopia.vercel.app/" target='_blank' rel="noopener noreferrer">Live Demo</a></p>
          </div>
        </div>
        <hr />
        <div className='projectitem'>
          <h3>Project 2: Interpretations Management App</h3>
          <p>
            About:
            Effortlessly manage interpretations with this Next.js app backed by AppWriter.
          </p>
          <p>
            View, edit, and delete interpretations with ease.
            Simplify your interpretation management tasks today! 🌟
          </p>
          <p>
            This web application allows users to manage interpretations,
            providing a platform to view, edit,
            and delete interpretations stored in the database.
          </p>
          <p>
            It utilizes Next.js for the frontend and AppWriter as the backend service.
          </p>
          <p>
            Role: Full Stack Developer
          </p>
          <div>
            <p>Technologies Used:</p>
            <ul>
              <li>Frontend: Next.js, React. The foundation for building React applications with server-side rendering.</li>
              <li>Backend: AppWriter.</li>
              <li>Tailwind CSS: A utility-first CSS framework for building modern and responsive designs.</li>
            </ul>
          </div>
          <div>
            <p>Features:</p>
            <ul>
              <li>View Interpretations: 👀 Users can view a list of interpretations fetched from the backend.</li>
              <li>Edit Interpretations: ✏️ Users can navigate to edit interpretation pages for making changes.</li>
              <li>Delete Interpretations: 🗑️ Users can delete interpretations directly from the list.</li>
            </ul>
          </div>
          <div>
            <p>Outcome:</p>
            <ul>
              <li>The Interpretations Management App is a web application designed for users to manage interpretations.</li>
              <li>It offers features such as viewing, editing, and deleting interpretations.</li>
              <li>The frontend is built using Next.js and React, while the backend utilizes AppWriter.</li>
              <li>Users can easily install and set up the app, and it provides REST API endpoints for fetching and deleting interpretations.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/Interpretations-Management-App" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
            <p><a href="https://gginterpretations.vercel.app/" target='_blank' rel="noopener noreferrer">Live Demo</a></p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Projects;
