import React from 'react';

const Projects = () => {
  return (
    <div className="container">
      <br />
      <br />
      <br />
      <br />
      <div className="project">
        <h2>Projects</h2>

        {/* Project 1 */}
        <div className='projectitem'>
          <h3>Quizopia</h3>
          <p>
            About:
            Quizopia is a Marvel-themed quiz application that tests your knowledge about Marvel characters and their universe.
            The app includes detailed character profiles and a variety of quiz questions to challenge users.
          </p>
          <p>
            Role: Full Stack Developer
          </p>
          <div>
            <p>Technologies Used:</p>
            <ul>
              <li>Next.js: A React framework for building fast and user-friendly web applications.</li>
              <li>HTML & CSS: For structuring and styling the web pages.</li>
              <li>JavaScript: The programming language used for developing the application logic.</li>
              <li>JSON: Used to retrieve data from the API for character profiles and quiz questions.</li>
            </ul>
          </div>
          <div>
            <p>Features:</p>
            <ul>
              <li>Character Profiles: Detailed profiles for each character, including descriptions, skills, images, and more.</li>
              <li>Quiz Questions: A wide range of questions covering different Marvel characters and their stories.</li>
              <li>User-friendly Interface: Easy-to-use interface for seamless quiz taking.</li>
            </ul>
          </div>
          <div>
            <p>Outcome:</p>
            <ul>
              <li>The Quizopia website effectively provides a platform for Marvel fans to test their knowledge.</li>
              <li>It features comprehensive character profiles and a variety of quiz questions, enhancing user engagement.</li>
              <li>The intuitive interface ensures a seamless user experience, making it enjoyable to use.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/ggquizopia" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
            <p><a href="https://ggquizopia.vercel.app" target='_blank' rel='noopener noreferrer'>Live Demo</a></p>
          </div>
        </div>

        {/* Project 2 */}
        <div className='projectitem'>
          <h3>GGReplicater</h3>
          <p>
            About:
            GGReplicater is a web application hosted on Vercel that utilizes Replicate AI to generate images based on user prompts.
          </p>
          <p>
            Role: Full Stack Developer
          </p>
          <div>
            <p>Technologies Used:</p>
            <ul>
              <li>Next.js: The foundation for building React applications with server-side rendering.</li>
              <li>Replicate AI: Advanced AI algorithms power our image generation.</li>
              <li>Tailwind CSS: A utility-first CSS framework for building modern and responsive designs.</li>
            </ul>
          </div>
          <div>
            <p>Features:</p>
            <ul>
              <li>Generate Images: Input a prompt and receive an AI-generated image in response.</li>
              <li>Download Images: Download the generated image with ease.</li>
              <li>Open Source: GGReplicater is built on open-source technologies, encouraging collaboration and innovation.</li>
            </ul>
          </div>
          <div>
            <p>Outcome:</p>
            <ul>
              <li>GGReplicater provides an easy-to-use platform for generating images based on user prompts.</li>
              <li>It promotes creativity by allowing users to visualize their ideas through AI-generated images.</li>
              <li>The open-source nature of the project encourages community contributions and further innovation.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/ggreplicater" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
            <p><a href="https://ggreplicater.vercel.app/" target='_blank' rel="noopener noreferrer">Live Demo</a></p>
          </div>
        </div>

        {/*Project 3*/}
        <div className='projectitem'>
          <h3>Promptopia</h3>
          <p>
            About:
            Promptopia is your go-to open-source AI prompting tool,
            designed to ignite your creativity.
          </p>
          <p>
            Discover, create,
            and share captivating prompts generated by advanced artificial intelligence.
            Dive into the world of inspiration with Promptopia!
          </p>
          <p>
            Role: Full Stack Developer
          </p>
          <div>
            <p>Technologies Used:</p>
            <ul>
              <li>Next.js: The foundation for building React applications with server-side rendering.</li>
              <li>AI Algorithms: Advanced algorithms power our prompt generation, providing unique and engaging content.</li>
              <li>Tailwind CSS: A utility-first CSS framework for building modern and responsive designs.</li>
            </ul>
          </div>
          <div>
            <p>Outcome:</p>
            <ul>
              <li>The Promptopia website effectively communicates its purpose as an AI prompting tool for igniting creativity.</li>
              <li>It features clear instructions for getting started, guidelines for usage and contributions, and acknowledges the technologies used.</li>
              <li>The user-friendly interface and transparent information make it a valuable resource for creative individuals.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/promtopia" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
            <p><a href="https://ggpromtopia.vercel.app/" target='_blank' rel="noopener noreferrer">Live Demo</a></p>
          </div>
        </div>

        {/*Project 4*/}
        <div className='projectitem'>
          <h3>Interpretations Management App</h3>
          <p>
            About:
            Effortlessly manage interpretations with this Next.js app backed by AppWriter.
          </p>
          <p>
            View, edit, and delete interpretations with ease.
            Simplify your interpretation management tasks today!🌟
          </p>
          <p>
            This web application allows users to manage interpretations,
            providing a platform to view, edit,
            and delete interpretations stored in the database.
          </p>
          <p>
            It utilizes Next.js for the frontend and AppWriter as the backend service.
          </p>
          <p>
            Role: Full Stack Developer
          </p>
          <div>
            <p>Technologies Used:</p>
            <ul>
              <li>Frontend: Next.js, React. The foundation for building React applications with server-side rendering.</li>
              <li>Backend: AppWriter.</li>
              <li>Tailwind CSS: A utility-first CSS framework for building modern and responsive designs.</li>
            </ul>
          </div>
          <div>
            <p>Features:</p>
            <ul>
              <li>View Interpretations: 👀 Users can view a list of interpretations fetched from the backend.</li>
              <li>Edit Interpretations: ✏️ Users can navigate to edit interpretation pages for making changes.</li>
              <li>Delete Interpretations: 🗑️ Users can delete interpretations directly from the list.</li>
            </ul>
          </div>
          <div>
            <p>Outcome:</p>
            <ul>
              <li>The Interpretations Management App is a web application designed for users to manage interpretations.</li>
              <li>It offers features such as viewing, editing, and deleting interpretations.</li>
              <li>The frontend is built using Next.js and React, while the backend utilizes AppWriter.</li>
              <li>Users can easily install and set up the app, and it provides REST API endpoints for fetching and deleting interpretations.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/Interpretations-Management-App" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
            <p><a href="https://gginterpretations.vercel.app/" target='_blank' rel="noopener noreferrer">Live Demo</a></p>
          </div>
        </div>

        {/*Project 5*/}
        <div className='projectitem'>
          <h3>Java Swing Registration & Quiz App</h3>
          <p>
            About:
            An intuitive Java Swing application for user registration, login, and a fun quiz experience.
            Seamlessly register, login securely, and test your knowledge with an interactive quiz.
            Save user credentials and quiz results for easy access.
          </p>
          <p>
            This Java Swing application provides a sleek and user-friendly interface for user registration, login, and an online quiz.
            It features a modern design with intuitive controls and seamless functionality.
          </p>
          <div>
            <p>Features:</p>
            <ul>
              <li>🔐 User Registration: Easily register with a username, password, security question, and answer.</li>
              <li>🔑 User Login: Conveniently log in with your registered credentials.</li>
              <li>❓ Forgot Password: Retrieve your password by answering the security question.</li>
              <li>📝 Online Quiz: Engage in an interactive online quiz experience.</li>
              <li>🏆 Quiz Result: View your quiz score along with your name.</li>
            </ul>
          </div>
          <div>
            <p>How to Use:</p>
            <ul>
              <li>Registration: Click on the "Register" button. Enter your desired username, password, security question, and answer.
                Click "Register" to complete the registration process.</li>
              <li>Login: Enter your username and password. Click "Login" to access your account.</li>
              <li>Forgot Password: If you forget your password, click on the "Forgot Password?" button.
                Enter your username and answer the security question to retrieve your password.</li>
              <li>Take Quiz: Upon logging in, click on the "Login" button to proceed. Answer the quiz questions.
                Click "Submit" to view your quiz score.</li>
            </ul>
          </div>
          <div>
            <p>Persistence:</p>
            <ul>
              <li>📄 Registered User Credentials: User registration information is securely saved and can be accessed anytime.</li>
              <li>📊 Quiz Results: Your quiz scores are stored with your name for future reference.</li>
            </ul>
          </div>
          <div>
            <p>File Structure:</p>
            <ul>
              <li>LoginApp.java: Main class for the login application.</li>
              <li>User.java: Class representing a user with registration information.</li>
              <li>UserDatabase.java: Class handling user data loading and saving.</li>
              <li>ForgotPasswordApp.java: Class for handling password retrieval.</li>
              <li>OnlineTest.java: Class for conducting the online quiz.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/Java-Swing-Registration-Quiz-App" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
          </div>
        </div>

        {/*Project 6*/}
        <div className='projectitem'>
          <h3>Java Swing Login-Quiz App</h3>
          <p>
            About:
            A user-friendly Java Swing-based login application with password visibility control and "Forgot Password?" recovery. Features secure authentication, clean styling, and an intuitive interface.
          </p>
          <p>
            This is a simple Java Swing-based login application designed for user authentication. The application provides a user interface for entering a username and password, with an option to show/hide the password. Additionally, it includes a "Forgot Password?" feature allowing users to recover their passwords through a security question.
          </p>
          <div>
            <p>Features:</p>
            <ul>
              <li>Login Form: Users can enter their username and password to log in.</li>
              <li>Show Password: Checkbox to toggle the visibility of the entered password.</li>
              <li>Forgot Password: Users can recover their passwords by answering a security question.</li>
              <li>Styling: The application features a clean and intuitive user interface with proper styling.</li>
            </ul>
          </div>
          <div>
            <p>How to Run:</p>
            <ul>
              <li>Ensure you have the Java Development Kit (JDK) installed.</li>
              <li>Compile and run the LoginApp class.</li>
              <code>
                javac LoginApp.java
                <br />
                java LoginApp
              </code>
              <li>The application window will appear, allowing users to log in or recover their passwords.</li>
            </ul>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/Java-Swing-Login-Quiz-App" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
          </div>
        </div>

        {/*Project 7*/}
        <div className='projectitem'>
          <h3>HTML Converter</h3>
          <p>
            This Java program converts text files into HTML files, adding basic styling and including the filename as a heading.
          </p>
          <p>
            The Main class in this project takes input from a text file and generates an HTML file with the same content. It adds basic styling to the HTML file and includes the filename as a heading.
          </p>
          <div>
            <p>Usage:</p>
            <ul>
              <li>Input File: Provide the path or filename of the text file you want to convert when prompted.</li>
              <li>Output File: The program generates an HTML file with the same name as the input file but with the .html extension.</li>
            </ul>
          </div>
          <div>
            <p>Prerequisites:</p>
            <ul>
              <li>Java Development Kit (JDK) installed on your system.</li>
              <li>Eclipse IDE (or any Java IDE) for development.</li>
            </ul>
          </div>
          <div>
            <p>How to Run:</p>
            <ul>
              <li>Clone this repository to your local machine.</li>
              <li>Open the project in your preferred Java IDE.</li>
              <li>Compile and run the Main class.</li>
              <li>Follow the instructions to input the filename or path.</li>
            </ul>
          </div>
          <div>
            <p>Example:</p>
            <p>Suppose you have a text file named example.txt with the content "Hello, world! This is a sample text file."
              Running the program with example.txt as input will generate example.html containing the HTML representation of the text.</p>
          </div>
          <div>
            <p><a href="https://github.com/gaureshpai/filetohtmlfileconvertor" target='_blank' rel="noopener noreferrer">GitHub Repository</a></p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Projects;
